# Generated by Django 4.2.2 on 2023-06-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_project", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reminder_date",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_day",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="reminder_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
