# Generated by Django 4.2.2 on 2023-06-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_project", "0003_task_reminder_date_task_reminder_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="reminder_yearly_date",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
