# Generated by Django 4.2.2 on 2023-07-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_project", "0004_task_reminder_yearly_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_access_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
