# Generated by Django 4.2.2 on 2023-07-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_project", "0005_user_google_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_credentials",
            field=models.TextField(blank=True, null=True),
        ),
    ]
