# Generated by Django 4.2.2 on 2023-07-04 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study_project", "0006_user_google_credentials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="google_access_token",
        ),
    ]
